image: Ubuntu2004  # образ для сборки

stack: jdk 11  # версия JDK

branches:
  only:
    - main  # ветка git

build: off  # будем использовать свой скрипт сборки

install:
  # запускаем SUT (& означает, что в фоновом режиме не блокируем терминал для запуска тестов)
  - java -jar ./artifacts/app-order.jar &
test_script:
  - ./gradlew test --info  # запускаем тест, флаг --info позволяет выводить больше информации
on_finish:
  - 7z a build/reports.zip build/reports/
  - appveyor PushArtifact build/reports.zip